### ISSUE TITLE
Undefined behavior in XBART.Probit

### ISSUE THREAD

**Issue by grantbrown** [JingyuHe/XBART#86]
While exploring the package, I noticed that you have a lot of compiler warnings and decided to run a quick test through Valgrind. It looks like there is indeed a lot of undefined behaviour going on, at least in XBART.Probit using my (potentially flawed) inputs. 

[Here's the test R code I ran.](https://gist.github.com/grantbrown/bf6beab5dae343bad63bc7b24f9fa694)

[Here's the valgrind output](https://gist.github.com/grantbrown/8c1422ec1c29be2ef092b4782e78dd7c), obtained with:

`valgrind --trace-children=yes --track-origins=yes R CMD BATCH class_test.R` 

I haven't had a chance to dig any deeper, but thought this output might be helpful.

**Comment by saaryalov** [comment]
The undefined behavior is likely due to the fact that the probit model only supports 1D matricies. Here is an [example](https://gist.github.com/saaryalov/df7aaa7147de3790d4f0e7d54ab5128b) of how to correctly use the probit class.  

This issue was still useful as we it brought to my attentions that we did not check for dimensions in the R version (which is why you were able to do this in the first place). Now your code should fail with error. 

We are still working on removing some of the warnings.  Thank you for bringing this to our attention.
